### ISSUE TITLE
Logs for the Feed update

### ISSUE THREAD

**Issue by lucashmsilva** [Yetangitu/Spodcast#7] opened 2022-02-26 20:24 UTC
Is there any logs for the feed update that is set inside the web application? My feeds are not fetching new episodes automatically even after many days the new episode is available in Spotify. When I manually use the "refresh" feature the the episode is fetched. With some logs I'll to check if the schedule is acctually running or any errors are occuring.

**Comment by lucashmsilva** [comment] 2022-02-27 14:48
I have Updated the schedule configuration througth that button, but after checking for the cron job installation I noticed that it was not even installed. The command you suggested returns `no crontab for www-data`. The php-fpm log file is clean and the nginx error log has nothing special either. Is it possible to be some privilege restriction to update the crontab?

**Comment by Yetangitu** [comment] 2022-02-27 20:17
Yes, it is possible for the web-user to not be allowed to have a _crontab._. Which OS do you run, and what version?

**Comment by lucashmsilva** [comment] 2022-02-27 20:40
Currently I'm running in a Digital Ocean Droplet with Ubuntu 20.04. The setup is a little convoluted... I run a Nginx Docker Container and a local installation of Spodcast.

**Comment by Yetangitu** [comment] 2022-02-28 15:45
The web user should be able to create cron jobs _and_ should be able to write to the _Spodcast_ root path. If either of these conditions are not met, updates will not work. The most likely problem here is that you're using a Docker container for your web server as these normally do not support cron jobs. There are [workarounds](https://www.cloudsavvyit.com/9033/how-to-use-cron-with-your-docker-containers/) but these are quite convoluted. The best solution here is probably to either use a normal _nginx_ install or add _cron_ to your _nginx_ Docker image.

An alternative would be to use web cron, I can add an endpoint for this in the next release.

**Comment by lucashmsilva** [comment] 2022-02-28 18:00
Yhea.. as I run other stuff in this server that I didn't want to risk breaking, I manually created a Cron job on the server (host, not the container) that is just a curl to the refresh URL. One job for each feed. I think we can close this issue, as it's not a problem with Spodcast. 

Thanks, for the help and for this awesome piece of code!

**Comment by Yetangitu** [comment] 2022-02-28 19:54
The next version - coming soon - will have a web cron endpoint, that should make things easier. Closing this issue.

**Closed by Yetangitu** 2022-02-28 19:54 UTC

**Comment by Yetangitu** [comment] 2022-03-01 23:50
The latest release contains both the mentioned web cron endpoint as well as some logging settings. To use webcron simply point any web client - curl or wget do wonders here - at:

`SPODCAST_URL/?action=update_shows`

This will initiate a feed update for all shows, using their respective `sync` and `keep` settings. At the end of the update it will return a json-encoded report on its activities. The verbosity of that report depends on the setting of the log level, this can be done in the settings screen.

Give it a try and let me know if it works as intended.

**Comment by Yetangitu** [comment] 2022-03-01 23:52
Oops, problem with 0.4.1, wait 'till 0.4.2...

**Comment by Yetangitu** [comment] 2022-03-02 00:03
Fixed now, 0.4.2 is up on Github and PyPi

**Comment by lucashmsilva** [comment] 2022-03-02 21:37
Thanks!! I'll give it a try here and let you know
